from enum import Enum


class ItemName(Enum):
    FISHING_ROD   = "ანკესი",
    HUNTING_RIFLE = "სანადირო თოფი",
    SHOVEL        = "ნიჩაბი",
    COMMON_FISH   = "უბრალო თევზი",
    RARE_FISH     = "წითელი თევზი",
    TROPICAL_FISH = "ტროპიკული თევზი",
    SHARK         = "ზვიგენი",
    GOLDEN_FISH   = "ოქროს თევზი",
    PIG           = "გოჭი",
    DEER          = "ირემი",
    BEAR          = "დათვი",
    WOLF          = "მგელი",
    TIGER         = "ვეფხვი",
    LION          = "ლომი",
    ELEPHANT      = "სპილო",
    COPPER_COIN   = "სპილენძის მონეტა",
    EMERALD       = "ზურმუხტი",
    RUBY          = "ლალი",
    SAPPHIRE      = "ფირუზი",
    AMETHYST      = "ამეთვისტო",
    DIAMOND       = "ბრილიანი",
    KNIFE         = "დანა",
